SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";



INSERT INTO `questions` (`id`, `type`, `majorQ`, `text`, `pics`, `level`, `score`, `time`, `section`, `isSelected`, `sequence`, `correct_answer`, `correct_answer_description`, `majorpics`, `underline`) VALUES
('BIOCH01A', 'BIOCHEMISTRY', NULL, 'Carbon monoxide ยับยั้ง complex ใดในกระบวนการ electron transport chain', NULL, 'EASY', 3.0, 45.0, 'A', NULL, NULL, 'Complex IV / IV / 4 / Cytochrome c Oxidase', NULL, NULL,NULL),
('PHYS02A', 'PHYSIOLOGY', NULL, 'เด็กชายอายุ 12 ปี เดินสะดุดบันไดล้มและมีบาดแผลเลือดไหล  Coagulation factor ใดที่จะทำงานในขั้นตอนแรกของ Extrinsic pathway of coagulation (Technical Term)', NULL, 'MEDIUM', 5.0, 60.0, 'A', NULL, NULL, 'Tissue factor/Tissue thromboplastin/Thromboplastin/Factor III', NULL, NULL,NULL),
('ANAT03A', 'ANATOMY', NULL, 'จากภาพตำแหน่งที่ลูกศรชี้สามารถคลำชีพจรของหลอดเลือดใดได้ (Technical term) ', 'ANAT03A', 'MEDIUM', 5.0, 60.0, 'A', NULL, NULL, 'Radial artery ', NULL, NULL,NULL),
('PHYS04A', 'PHYSIOLOGY', NULL, 'นักเรียนชายอายุ 18 ปี มีอาการตัวร้อนมาก มึนงง คลื่นไส้ หัวใจเต้นเร็ว และหมดสติไป ระหว่างทำกิจกรรมกลางแดดในวันที่มีอุณหภูมิ 39 องศาเซลเซียส และความชื้นสูงเป็นเวลานาน กลไกในการระบายความร้อน (Heat loss mechanism) ที่สำคัญใดทำงานน้อยลงในกรณีนี้ ', NULL, 'EASY', 3.0, 45.0, 'A', NULL, NULL, 'Evaporation / Sweating ', NULL, NULL,NULL),
('MICRO05A', 'MICROLOGY', NULL, 'ผู้ป่วยชายอายุ 40 ปี มีอาการท้องเสียอย่างรุนแรง อาเจียนและถ่ายเหลวเป็นน้ำเป็นเวลา 2 วัน โดยเมื่อ 4 วันก่อนหน้านี้ เขาได้เดินทางกลับมาจากการท่องเที่ยวที่ประเทศอินเดีย จากการตรวจพบว่าคนไข้มีภาวะขาดน้ำ และมี electrolyte imbalance แพทย์จึงได้ทำการเพาะเชื้อจากอุจจาระของคนไข้บน TCBS agar และได้ผลดังภาพ จงบอกชื่อของ toxin ที่ส่งผลให้เกิดภาวะขาดน้ำในคนไข้รายนี้ (Technical term)', 'MICRO05A', 'HARD', 7.0, 75.0, 'A', NULL, NULL, 'Cholera (toxin)', NULL, NULL,NULL),
('ANAT06A', 'ANATOMY', NULL, 'จงบอกชื่อเฉพาะของบริเวณที่ชี้ (Technical term) ', 'ANAT06A', 'EASY', 3.0, 45.0, 'A', NULL, NULL, 'Aortic arch / Arch of aorta ', NULL, NULL,NULL),
('MICRO07A', 'MICROLOGY', NULL, 'ผู้ป่วยชายอายุ 5 ปี มีอาการไข้และน้ำมูกไหล ตรวจร่างกายเบื้องต้นพบผื่นแดงสดบนแก้ม ตามภาพ A และพบผื่นแดงเป็นร่างแหที่บริเวณแขน ขาและลำตัว ตามภาพ B จงบอกชื่อและสายพันธุ์ของเชื้อก่อโรคในคนไข้รายนี้ ', 'MICRO07A', 'MEDIUM', 5.0, 60.0, 'A', NULL, NULL, 'Human parvovirus B19 / Parvovirus B19 / Erythrovirus B19 ', NULL, NULL,NULL),
('BIOCH08A', 'BIOCHEMISTRY', NULL, 'ชาย 23 ปี มีอาการไข้สูง แพทย์ตรวจร่างกายพบภาวะซีดและตัวเหลืองเล็กน้อย จากการซักประวัติเพิ่มเติมพบว่าคนไข้มีอาการปัสสาวะเป็นสีดำเข้มหลังจากใช้ยาหยอดตา Chloramphenicol เข้าไปเป็นจำนวนมาก จากการตรวจทางห้องปฏิบัติการพบลักษณะของเม็ดเลือดแดงตามภาพ Metabolism ใดที่มีความผิดปกติในคนไข้รายนี้ (Full name) ', 'BIOCH08A', 'HARD', 7.0, 75.0, 'A', NULL, NULL, 'Pentose Phosphate Pathway ', NULL, NULL,NULL),
('PHYS09A', 'PHYSIOLOGY', NULL, 'จากภาพ Neuromuscular junction แสดงการหลั่ง Neurotransmitter ชนิดหนึ่ง (จุดสีฟ้า) เอนไซม์ใดย่อยสลาย Neurotransmitter ชนิดนี้ (Technical Term)', 'PHYS09A', 'EASY', 3.0, 45.0, 'A', NULL, NULL, 'Acetylcholinesterase', NULL, NULL,NULL),
('ANAT10A', 'ANATOMY', NULL, 'จากภาพคือความผิดปกติที่เรียกว่า Popeye deformity ซึ่งเป็นภาวะที่เกิดจากการฉีกขาดของ tendon ของกล้ามเนื้อที่ชื่อว่าอะไร (Technical Term)', 'ANAT10A', 'MEDIUM', 5.0, 60.0, 'A', NULL, NULL, 'Biceps brachii muscle ', NULL, NULL,NULL),
('BIOCH11A', 'BIOCHEMISTRY', NULL, 'ในกระบวนการ transcription ของแบคทีเรีย กำหนดให้ ลำดับเบสของ antisense strand ของ DNA สายหนึ่งเป็น 5’- AGTTCGCAAC -3’ จงเขียนลำดับเบสของ mRNA ที่สังเคราะห์ได้จาก DNA เส้นดังกล่าว ', NULL, 'EASY', 3.0, 45.0, 'A', NULL, NULL, '5’- GUUGCGAACU -3’  ', NULL, NULL,NULL),
('ANAT12A', 'ANATOMY', NULL, 'จากภาพ CT scan ระดับอก กำหนดให้ หมายเลข 1 คือ หัวใจห้องล่างซ้าย และหมายเลข 2 คือ ตับ แล้วโครงสร้างหมายเลข 3 คือหลอดเลือดที่มีชื่อว่าอะไร (Full name) ', 'ANAT12A', 'HARD', 7.0, 75.0, 'A', NULL, NULL, 'Inferior vena cava ', NULL, NULL,NULL),
('PARA13A', 'PARASITE', NULL, 'ชายไทยอายุ 35 ปี มีอาการท้องอืด แน่นท้อง มีความรู้สึกท้องเดินและเหมือนมีอะไรบางอย่างเคลื่อนตัวในท้อง จึงได้ซื้อยาถ่ายพยาธิ Niclosamide มากินเอง เมื่ออุจจาระออกมาพบสิ่งแปลกปลอมดังภาพ อะไรคือปัจจัยเสี่ยงที่ทำให้ผู้ป่วยติดเชื้อปรสิตชนิดนี้ ', 'PARA13A', 'MEDIUM', 5.0, 60.0, 'A', NULL, NULL, 'Eating raw beef/pock , Eating undercooked raw beef/pock ', NULL, NULL,NULL),
('ANAT14A', 'ANATOMY', NULL, 'จากภาพเนื้อเยื่อดังกล่าวเจริญมาจากชั้นใดของ Trigerminal layer ในระยะตัวอ่อน (Technical term) ', 'ANAT14A', 'EASY', 3.0, 45.0, 'A', NULL, NULL, 'Mesoderm ', NULL, NULL,NULL),
('PHYS15A', 'PHYSIOLOGY', NULL, 'จากภาพ Wiggers diagram (ภาพ A) ระยะที่ลูกศรชี้มีชื่อว่าอะไร (Technical Term) และตรงกับตำแหน่งหมายเลขใดในกราฟ P-V loop (ภาพ B) ', 'PHYS15A', 'HARD', 7.0, 75.0, 'A', NULL, NULL, '- Isovolumetric ventricular contraction / หมายเลข 2', NULL, NULL,NULL),
('MICRO16A', 'MICROLOGY', NULL, 'จงบอกชื่อ genus ของเชื้อก่อโรคในภาพ', 'MICRO16A', 'EASY', 3.0, 45.0, 'A', NULL, NULL, 'Aspergillus ', NULL, NULL,NULL),
('BIOCH17A', 'BIOCHEMISTRY', NULL, 'ผลิตภัณฑ์ 3 คาร์บอนจาก beta oxidation ของกรดไขมันอิ่มตัวที่มีคาร์บอนเป็นเลขคี่จะถูกเปลี่ยนรูปไปเป็นสารใดใน Kreb’s cycle', NULL, 'MEDIUM', 5.0, 60.0, 'A', NULL, NULL, 'Succinyl CoA ', NULL, NULL,NULL),
('PARA18A', 'PARASITE', NULL, 'เด็กชายอายุ 4 ปี มีอาการคันที่บริเวณรอบๆทวารหนักในเวลากลางคืน แพทย์ตรวจร่างกายและตรวจโดยนำเทปกาวใสมาทาบบริเวณรูทวาร (Scotch tape technique) จากนั้นนำไปส่องด้วยกล้องจุลทรรศน์ พบไข่พยาธิที่มีตัวพยาธิขนาดเล็กลักษณะดังภาพ จงให้การวินิจฉัยโรค (Technical term)', 'PARA18A', 'HARD', 7.0, 75.0, 'A', NULL, NULL, 'Enterobiasis / Enterobius vermicularis infection ', NULL, NULL,NULL),
('ANAT01B', 'ANATOMY', NULL, 'จงบอก Anatomical movement ของข้อเท้า ดังแสดงในภาพ (Technical term) ', 'ANAT01B', 'EASY', 3.0, 45.0, 'B', NULL, NULL, 'Eversion ', NULL, NULL,NULL),
('MICRO02B', 'MICROLOGY', NULL, 'ตารางแสดงการระบาดใหญ่ทั่วโลก (Pandemic) ของไวรัส Influenza Subtype A ระหว่างปี ค.ศ.1947-2003 จงบอกชื่อของกระบวนการที่ส่งผลให้ไวรัสชนิดนี้สามารถระบาดใหญ่ทั่วโลกได้เป็นจำนวนบ่อยครั้งแม้มีการผลิตวัคซีนที่มีความจำเพาะต่อสายพันธุ์ของไวรัส (Technical Term)', 'MICRO02B', 'MEDIUM', 5.0, 60.0, 'B', NULL, NULL, 'Antigenic shift / Major antigenic changes / Genetic reassortment ', NULL, NULL,NULL),
('BIOCH03B', 'BIOCHEMISTRY', NULL, 'การวัดระดับการแสดงออกของ oncogenes ในเซลล์มะเร็ง การเพิ่มปริมาณสารพันธุกรรมให้มีปริมาณเพียงพอ สำหรับการตรวจหาระดับการแสดงออกของยีนดังกล่าวควรใช้เทคนิคใด (Full name)', NULL, 'HARD', 7.0, 75.0, 'B', NULL, NULL, 'Reverse transcription polymerase chain reaction / Reverse transcription quantitative polymerase chain reaction', NULL, NULL,NULL),
('PHYS04B', 'PHYSIOLOGY', NULL, 'Antigen presenting cell ชนิดใด สามารถกระตุ้นการทำงานของ CD4+ T-cell ผ่าน MHC class II ได้ จงระบุชื่อเซลล์มา 2 ชนิด (Technical Term)', NULL, 'EASY', 3.0, 45.0, 'B', NULL, NULL, 'B/B lymphocyte/B cell/Macrophage/Dendritic cell', NULL, NULL,NULL),
('BIOCH05B', 'BIOCHEMISTRY', NULL, 'ผู้ป่วยชาย อายุ 6 เดือน มีอาการผื่นและแผลตามร่างกาย ร่วมกับอาการมือสั่น แพทย์ตรวจร่างกายพบ สีตา, สีผิวหนัง, สีผม ซีดขาวกว่าปกติ แม่ของเด็กให้ประวัติว่าปัสสาวะลูกมีกลิ่นฉุน แพทย์ส่งตรวจเลือดพบ Hyperphenylalaninemia ผู้ป่วยรายนี้ไม่สามารถเปลี่ยน Phenylalanine เป็นสารใดได้', NULL, 'MEDIUM', 5.0, 60.0, 'B', NULL, NULL, 'Tyrosine', NULL, NULL,NULL),
('ANAT06B', 'ANATOMY', NULL, 'จากฟิล์ม X-ray จงระบุชื่อกระดูกที่หัก (Technical term) ', 'ANAT06B', 'EASY', 3.0, 45.0, 'B', NULL, NULL, 'Radius / Radial bone ', NULL, NULL,NULL),
('PHYS07B', 'PHYSIOLOGY', NULL, 'ผู้ป่วยชายอายุ 65 ปี มีอาการอ่อนเพลีย เหนื่อยง่าย เลือดออกง่าย และคันตามผิวหนัง แพทย์ตรวจร่างกายพบอาการตัวเหลือง ตาเหลือง ท้องมาน เท้าบวม และมีฝ่ามือแดง จากการตรวจเพิ่มเติมแพทย์วินิจฉัยว่าเป็น Right-side heart failure  ผู้ป่วยรายนี้มีการเปลี่ยนแปลงอย่างไร [เพิ่มขึ้น/ลดลง] 1. Hydrostatic pressure 2. Oncotic pressure', NULL, 'MEDIUM', 5.0, 60.0, 'B', NULL, NULL, '1. Hydrostatic pressure เพิ่มขึ้น / 2. Oncotic pressure ลดลง', NULL, NULL,NULL),
('PARA08B', 'PARASITE', NULL, 'ผู้ป่วยชายอายุ 21 ปี มีอาการไข้ หนาวสั่น  หลังจากกลับจากค่ายอาสาในแถบชนบทของจังหวัดแถบภาคตะวันตกของประเทศไทยประมาณ 2 สัปดาห์ หมอสั่งเจาะตรวจฟิล์มเลือด ผลพบเชื้อปรสิตในเลือดดังภาพ จงบอกชื่อ Genus พาหะนำโรคของเชื้อชนิดนี้ ', 'PARA08B', 'HARD', 7.0, 75.0, 'B', NULL, NULL, 'Anopholes', NULL, NULL,NULL),
('BIOCH09B', 'BIOCHEMISTRY', NULL, 'คนที่อาศัยอยู่ที่สูงนานๆ จะมีการผลิตสารใดสูงขึ้นในเม็ดเลือดแดง ทำให้ hemoglobin มี oxygen affinity ลดลง (Technical Term)', NULL, 'EASY', 3.0, 45.0, 'B', NULL, NULL, '2,3-BPG (2,3-Bisphosphoglycerate) หรือ 2,3-DPG (2,3-Diphosphoglycerate) ', NULL, NULL,NULL),
('PHYS10B', 'PHYSIOLOGY', NULL, 'เมื่อสูดดม Carbon monoxide ในปริมาณมากจนทำให้เกิดภาวะ CO poisoning กราฟ Oxygen dissociation curve จะมีลักษณะเป็นอย่างไรเมื่อเทียบกับกราฟที่แสดงดังภาพ [เลื่อนซ้าย/ขวา/ไม่เปลี่ยนแปลง] และ % hemoglobin saturation [เพิ่มขึ้น/ลดลง/ไม่เปลี่ยนแปลง]', 'PHYS10B', 'MEDIUM', 5.0, 60.0, 'B', NULL, NULL, 'กราฟเลื่อนไปทางซ้าย / % sat ต่ำลง', NULL, NULL,NULL),
('MICRO11B', 'MICROLOGY', NULL, 'การถ่ายทอดยีนในแบคทีเรียตามภาพเรียกว่ากระบวนการอะไร  (Technical Term)', 'MICRO11B', 'EASY', 3.0, 45.0, 'B', NULL, NULL, 'Transformation ', NULL, NULL,NULL),
('PHYS12B', 'PHYSIOLOGY', NULL, 'ผู้ป่วยชายอายุ 35 ปี มีอาการอ่อนเพลีย เบื่ออาหาร เหนื่อยง่าย และขับถ่ายไม่ปกติ แพทย์วินิจฉัยเป็น Pernicious anemia ภาวะโลหิตจางชนิดนี้เกิดจากการขาด Intrinsic factor ซึ่งหลั่งจากเซลล์ใด และมีผลต่อการดูดซึมสารใด ', NULL, 'HARD', 7.0, 75.0, 'B', NULL, NULL, '- Parietal cell- / Vitamin B12/Cyanocobalamin/Cobalamin', NULL, NULL,NULL),
('BIOCH13B', 'BIOCHEMISTRY', NULL, 'วิตามินใดเป็นสารตั้งต้นในการสังเคราะห์ coenzymes ของ AST ในการเร่งปฏิกิริยานี้', 'BIOCH13B', 'EASY', 3.0, 45.0, 'B', NULL, NULL, 'B6 (Pyridoxine) ', NULL, NULL,NULL),
('ANAT14B', 'ANATOMY', NULL, 'จากภาพคือผนังด้านในของลำไส้เล็กส่วน duodenum โครงสร้างที่เป็นรอยพับตามแนวขวางดังลูกศรชี้มีชื่อเรียกว่าอะไร (Technical Term)', 'ANAT14B', 'MEDIUM', 5.0, 60.0, 'B', NULL, NULL, 'Plica circularis / Plicae circulares / Circular folds ', NULL, NULL,NULL),
('MICRO15B', 'MICROLOGY', NULL, 'ผู้ป่วยหญิงอายุ 65 ปี มีอาการหายใจไม่สะดวก เหนื่อยหอบ และมีไข้สูง 39 องศาเซลเซียส โดยเมื่อ 1 สัปดาห์ก่อน เธอได้เข้าพักห้องแอร์ที่โรงแรมเก่าแห่งหนึ่ง ผลการตรวจ X-ray แสดงดังภาพ A นอกจากนี้ผลตรวจ gram stain ของเสมหะผู้ป่วย ไม่สามารถเห็นเชื้อก่อโรคได้อย่างชัดเจนแต่พบ Neutrophil ปริมาณมาก และจากการทำ microbial culture พบว่าเชื้อก่อโรคเจริญได้เฉพาะใน buffered charcoal yeast extract agar ดังแสดงในภาพ B จงวินิจฉัยโรคที่มีความเป็นไปได้มากที่สุดในผู้ป่วยรายนี้ (Technical term)', 'MICRO15B', 'HARD', 7.0, 75.0, 'B', NULL, NULL, 'Legionellosis/ Legionnaires'' disease/ Legionella infection', NULL, NULL,NULL),
('PHYS16B', 'PHYSIOLOGY', NULL, 'Collagen จะถูกย่อยครั้งแรกในทางเดินอาหารโดยเอนไซม์ที่มีชื่อว่าอะไร และ proenzyme ของเอนไซม์ดังกล่าวหลั่งออกมาจากเซลล์ใด (Technical Term)', NULL, 'EASY', 3.0, 45.0, 'B', NULL, NULL, '- Pepsin- / Chief cell', NULL, NULL,NULL),
('PARA17B', 'PARASITE', NULL, 'ผู้ป่วยชาย อายุ 49 ปี อาชีพเกษตรกร มาด้วยอาการแสบร้อนกลางอก ไอแห้ง หายใจหอบ มีเสียงหวีด แพทย์ให้ยาขยายหลอดลมไปแต่อาการไม่ดีขึ้น ผลตรวจ complete blood count พบว่า มี eosinophil สูง แพทย์ส่งตรวจอุจจาระ พบพยาธิลักษณะดังภาพ พยาธิชนิดนี้ติดต่อสู่คนได้อย่างไร', 'PARA17B', 'MEDIUM', 5.0, 60.0, 'B', NULL, NULL, 'Skin penetration', NULL, NULL,NULL),
('ANAT18B', 'ANATOMY', NULL, 'ชายอายุ 22 ปี มาโรงพยาบาลหลังจากประสบอุบัติเหตุทางรถจักรยานยนต์ ผลการตรวจ X-ray พบ left mid-humeral fracture และผลการตรวจร่างกายพบการอ่อนแรงของกล้ามเนื้อ triceps brachii แต่ผู้ป่วยยังพอสามารถ extend ข้อศอกได้บ้าง ส่วนกล้ามเนื้อบริเวณ posterior compartment of forearm อย่าง brachioradialis, extensor muscles of wrist เกิด paralysis นอกจากนี้แพทย์ยังพบ clinical sign ที่มีชื่อว่า wrist-drop จากประวัติและผลการตรวจร่างกายดังกล่าว ผู้ป่วยได้รับความเสียหายที่เส้นประสาทที่ชื่อว่าอะไร (Technical Term)', NULL, 'HARD', 7.0, 75.0, 'B', NULL, NULL, 'Radial Nerve ', NULL, NULL,NULL),
('ANAT99H', 'ANATOMY', NULL, 'จงบอกชื่อโครงสร้างที่ลูกศรชี้ (Technical Term)', 'ANATสำรอง', 'MEDIUM', 5.0, 60.0, 'NULL', NULL, NULL, 'Cystic duct ', NULL, NULL,NULL),
('PHYS99H', 'PHYSIOLOGY', NULL, 'หลังสิ้นสุดการหายใจออกเมื่อเทียบกับความดันชั้นบรรยากาศ จะทำให้ความดันมีค่าเป็นอย่างไร [มากกว่า/น้อยกว่า/เท่ากัน] 1. ความดันภายในถุงลม (Alveolar pressure) / 2. ความดันภายในช่องอก (Pleural pressure)', NULL, 'MEDIUM', 5.0, 60.0, 'NULL', NULL, NULL, '1. Alveolar pressure = เท่ากัน / 2. Pleural pressure = น้อยกว่า', NULL, NULL,NULL),
('BIOCH99H', 'BIOCHEMISTRY', NULL, 'ผู้ป่วยชายอายุ 40 ปี มีอาการปวดบวมแดงข้อนิ้วโป้งของเท้าซ้าย แพทย์ตรวจพบ hyperuricemia และพบลักษณะ tophi ที่ข้อนิ้วดังกล่าว ผู้ป่วยได้รับยา Allopurinol ยานี้ไปยับยั้ง enzyme ใดใน purine nucleotide metabolism', NULL, 'MEDIUM', 5.0, 60.0, 'NULL', NULL, NULL, 'Xanthine oxidase ', NULL, NULL,NULL),
('MICRO99H', 'MICROLOGY', NULL, 'ผู้ป่วยชายอายุ 9 ปี มีอาการปวดศีรษะรุนแรง มึนงง สับสนและมีไข้สูง แต่ไม่สามารถทานยาที่แพทย์สั่งได้เนื่องจากมีการหดเกร็งของหลอดอาหารทุกครั้งที่พยายามดื่มน้ำพร้อมกับยา และ 10 วันต่อมาผู้ป่วยได้เสียชีวิตลง จงบอกสาเหตุที่พบได้มากที่สุดของการติดเชื้อก่อโรคชนิดนี้', NULL, 'MEDIUM', 5.0, 60.0, 'NULL', NULL, NULL, 'Animal bites / scratch ', NULL, NULL,NULL),
('PARA99H', 'PARASITE', NULL, 'ผู้ป่วยเด็กชายอายุ 8 ปี มีอาการคลื่นไส้ เวียนหัว อาเจียนหลายรอบ แม่ของผู้ป่วยพบสิ่งแปลกปลอมพร้อมกับเศษอาหาร มีลักษณะเป็นเส้นยาว ขอบเขตชัดเจนดังภาพ  ผู้ป่วยติดเชื้อปรสิตชนิดอะไร ', 'PARAสำรอง', 'MEDIUM', 5.0, 60.0, 'NULL', NULL, NULL, 'Ascaris lumbricoides ', NULL, NULL,'Ascaris lumbricoides');
COMMIT;